name: Env and Context
on: push
env:
    DAY_OF_WEEK: Monday
  
jobs:
  greeting_job:
    name: Greeting Env And Context
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
  